project_name: "warrant"
task_prefix: "w"
default_status: "To Do"
statuses:
  - "To Do"
  - "In Progress"
  - "Done"
labels: []
milestones: []
auto_commit: false
remote_operations: false
id_server: "http://backlog.lan.stenmans.org"
